### PR TITLE
fix: periodically update bridgechain list

### LINKED ISSUE #1817: bug: the bridgechain list is not updated automatically after registration
After registering a bridgechain, the bridgechain list doesn't auto update. User is forced to either reload or change peer for it to show.

**Steps to Reproduce (for bugs)**

1. Go to wallet
2. Go to the secondary menu in the header
3. Click in Registration menu
4. Register  Bussines (if you don't have one)
5. Go to the Business tab
6. Register  Bridgechain (if you don't have one)
7. The bridgechain list is not updated automatically after registration

**Your Environment**

- Version used: ark-desktop-wallet 2.8.1
- Environment name and version: Chrome v80.0.3987.86 - Node.js v12.13.0
- Operating System and version: Ubuntu 19.10

### PR DESCRIPTION
**Pull request by brenopolanski**
## Summary

Fixes #1817.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I'm not sure this will work as expected because it only reloads the bridgechain list after submitting the transaction (unless I misunderstood). The problem is that the transaction isn't forged instantly. I think it's best to have a timer on that bridgechain list to keep refreshing the list every minute or so to check for changes

**Comment by brenopolanski** [comment]
> I'm not sure this will work as expected because it only reloads the bridgechain list after submitting the transaction (unless I misunderstood). The problem is that the transaction isn't forged instantly. I think it's best to have a timer on that bridgechain list to keep refreshing the list every minute or so to check for changes

@alexbarnsley what do you think: https://github.com/ArkEcosystem/desktop-wallet/commit/21ec4f25c102141c6b738050093a46ba06eb1c76#diff-cebae3f54745803997fc366f1bb91e3b ?

File: src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue [hunk 1]
```diff
@@ -122,12 +127,18 @@ export default {
...
+        if (!this.wallet_fromRoute || this.isFetching) {
+          return
+        }
 
-      this.isLoading = true
-      this.fetchBridgechains()
+        this.isLoading = true
+        this.fetchBridgechains()
+      } catch (error) {
+        throw new Error('It is not possible load bridgechain list')
```
Comment (alexbarnsley) [inline src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue]: I would log instead of throwing an error. I've experienced it where throwing an error has halted components meaning they don't work properly

Comment (brenopolanski) [reply src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue]: make sense :+1: I'll add the log

**Comment by alexbarnsley** [comment]
I partly think the fetchBridgechains method shouldn't clear the screen while loading. It looks weird because of the flicker where the data clears and re-appears 🤔
