### PR TITLE
fix: ark uri scheme

### LINKED ISSUE #2286: ark: uri scheme specifying address but no amount no longer works in 2.9.2
In 2.9.1 and earlier you could specify an `ark:` URI like `ark:AUexKjGtgsSpVzPLs6jNMM6vJ6znEVTQWK` which would pre-fill the modal with the address to send to, while allowing the user to specify the amount to send.

This is broken in 2.9.2 as it now brings up a default modal with nothing pre-filled, no address, nada. If you specify the amount then it works e.g. `ark:AUexKjGtgsSpVzPLs6jNMM6vJ6znEVTQWK?amount=1` but that is no good for situations where you don't know how much the user wants to send.

I've received complaints about this new unexpected behaviour from people playing the PVP wallet games since they can no longer start a new game easily, since it uses the former `ark:` URI structure i.e. an address with no amount, as it is supposed to pre-fill the game's wallet address in the modal but allow the user to enter their own desired amount so they can pick their own wager. This new unanticipated behaviour now causes a terrible user experience.

### PR DESCRIPTION
**Pull request by brenopolanski**
## Summary

Fixes #2286 

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

File: src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue [hunk 1]
```diff
@@ -573,6 +573,8 @@ export default {
               this.wallet_truncate(this.schema.address)
             ]))
           }
+        } else {
```
Comment (alexbarnsley) [inline src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue:576]: This bypasses the `validateAddress` check. You'll be better just to move the amount check I think

Comment (brenopolanski) [reply src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue:576]: It check first if there is a valid address. Then, if there was an `address` and `amount` it must be added to `recipients`, otherwise fill in the `recipientId` input.

**Comment by brenopolanski** [comment]
@samharperpittam can you test please?

**Comment by samharperpittam** [comment]
> @samharperpittam can you test please?

on it
