### PR TITLE
fix: custom peer host validation

### LINKED ISSUE #1298: Custom peer window labelling is unclear
**Current Behavior**

The current labelling on the ‘connect to custom peer’ window is unclear. The Host/IP field requires a protocol prefix but the field is labelled ‘IP/Host’ not URL, not is an example given (until you get it wrong)

The port field should be pre-filled with the default network port

**Possible Solution**

Give an example underneath the ‘IP/Host’ field, and rename it only to ‘host’ or ‘Server’

Pre-fill the port field with the default port.

[Issue reported in Slack]

### PR DESCRIPTION
**Pull request by davimello28**
## Summary

- Closes both issues on #1687
- Closes #1298 

## Checklist

*This is a temporary fix.*

- [X] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

File: src/renderer/components/Modal/ModalPeer.vue [hunk 1]
```diff
@@ -133,7 +133,9 @@ export default {
   mounted () {
     if (this.currentPeer) {
       if (this.currentPeer.host) {
-        this.form.host = this.currentPeer.host
+        const scheme = this.currentPeer.isHttps ? 'https://' : 'http://'
```
Comment (brenopolanski) [inline src/renderer/components/Modal/ModalPeer.vue]: You can move this line to the top, because `line 140` has the same code.

Example:

```
  mounted () {
    if (this.currentPeer) {
      const scheme = this.currentPeer.isHttps ? 'https://' : 'http://'
      
      if (this.currentPeer.host) {
        const hostname = new URL(this.currentPeer.host).hostname
        this.form.host = scheme + hostname
      } else if (this.currentPeer.ip) {
        this.form.host = `${scheme}${this.currentPeer.ip}`
      }

      if (this.currentPeer.port) {
        this.form.port = this.currentPeer.port
      }
    }
  }
```

File: src/renderer/components/Modal/ModalPeer.vue [hunk 2]
```diff
@@ -147,6 +149,10 @@ export default {
 
   methods: {
     emitConnect () {
+      const host = this.form.host
+      if (host.endsWith('/')) {
+        this.form.host = host.slice(0, -1)
+      }
```
Comment (brenopolanski) [inline src/renderer/components/Modal/ModalPeer.vue]: I tested using `////` at the end:

Screenshot from 2020-02-21 10-19-02

You may be able to create a recursive function to remove 1 or more slashes at the end. Like this:

```
    emitConnect () {
      const { host } = this.form
      const path = url => url.endsWith('/') ? path(url.slice(0, url.length - 1)) : url
      this.form.host = path(host)
      this.$emit('connect', {
        peer: this.form,
        closeTrigger: this.closeTrigger
      })
    }
```

Comment (davimello28) [reply src/renderer/components/Modal/ModalPeer.vue]: As I said before, I don't think that we should try to cover all the possibilities of input now. I have a task to refactor the whole peer system and this will probably be changed in a near feature.

I can make it recursive but the system should support paths for the peers. The application is not responsible for resolving the URLs.

File: src/renderer/components/Modal/ModalPeer.vue (hunk 1 above)
Comment (davimello28) [reply src/renderer/components/Modal/ModalPeer.vue]: Done!

File: src/renderer/components/Modal/ModalPeer.vue [hunk 3]
```diff
@@ -147,6 +149,10 @@ export default {
 
   methods: {
     emitConnect () {
+      const host = this.form.host
```
Comment (brenopolanski) [inline src/renderer/components/Modal/ModalPeer.vue]: Here you can use (destructuring): `const { host } = this.form`

File: src/renderer/components/Modal/ModalPeer.vue (hunk 2 above)
Comment (brenopolanski) [reply src/renderer/components/Modal/ModalPeer.vue]: Okay :+1:

**Comment by alexbarnsley** [comment]
@davimello28 are we keeping #1621 and this?
